export let usersData = [
  {
    userId: 0,
    username: 'admin',
    password: 'admin',
    role: 'ADMIN',
    title: 'Dr',
    firstName: 'admin',
    lastName: 'admin',
    job: 'admin',
    email: 'admin@gmail.com',
    academicDisciplines: [
      {academicDisciplineId: '02004013', academicDisciplineName: 'Painting'},
      {academicDisciplineId: '02004014', academicDisciplineName: 'Printmaking'},
      {academicDisciplineId: '02004015', academicDisciplineName: 'Sculpture'}
    ]

  },
  {
    userId: 1,
    username: 'author',
    password: 'author',
    role: 'author',
    title: 'Mr',
    firstName: '',
    lastName: '',
    job: '',
    email: '',
    academicDisciplines: [
      {academicDisciplineId: '02021003', academicDisciplineName: 'Other French and Francophone Language and Literature'},
      {academicDisciplineId: '02022', academicDisciplineName: 'German Language and Literature'},
      {academicDisciplineId: '02022001', academicDisciplineName: 'German Linguistics'},
      {academicDisciplineId: '02022002', academicDisciplineName: 'German Literature'},
      {academicDisciplineId: '02022003', academicDisciplineName: 'Other German Language and Literature'},
      {academicDisciplineId: '02023', academicDisciplineName: 'History'},
      {academicDisciplineId: '02023001', academicDisciplineName: 'African History'},
      {academicDisciplineId: '02023002', academicDisciplineName: 'Asian History'},
      {academicDisciplineId: '02023003', academicDisciplineName: 'Canadian History'},
      {academicDisciplineId: '02023004', academicDisciplineName: 'Cultural History'},
      {academicDisciplineId: '02023005', academicDisciplineName: 'Diplomatic History'},
      {academicDisciplineId: '02023006', academicDisciplineName: 'European History'},
      {academicDisciplineId: '02023007', academicDisciplineName: 'Genealogy'},
      {academicDisciplineId: '02023008', academicDisciplineName: 'History of Gender'},
      {academicDisciplineId: '02023009', academicDisciplineName: 'History of the Pacific Islands'},
      {academicDisciplineId: '02023010', academicDisciplineName: 'History of Religion'},
      {academicDisciplineId: '02023011', academicDisciplineName: 'History of Science, Technology, and Medicine'},
      {academicDisciplineId: '02023012', academicDisciplineName: 'Intellectual History'},
      {academicDisciplineId: '02023013', academicDisciplineName: 'Islamic World and Near East History'},
      {academicDisciplineId: '02023014', academicDisciplineName: 'Labor History'},
      {academicDisciplineId: '02023015', academicDisciplineName: 'Latin American History'},
      {academicDisciplineId: '02023016', academicDisciplineName: 'Legal'},
      {academicDisciplineId: '02023017', academicDisciplineName: 'Medieval History'},
      {academicDisciplineId: '02023018', academicDisciplineName: 'Military History'},
      {academicDisciplineId: '02023019', academicDisciplineName: 'Oral History'},
      {academicDisciplineId: '02023020', academicDisciplineName: 'Political History'},
      {academicDisciplineId: '02023021', academicDisciplineName: 'Public History'},
      {academicDisciplineId: '02023022', academicDisciplineName: 'Social History'},
      {academicDisciplineId: '02023023', academicDisciplineName: 'United States History'}
    ]

  },
  {
    userId: 2,
    username: 'reviewer',
    password: 'reviewer',
    role: 'reviewer',
    title: '',
    firstName: '',
    lastName: '',
    job: '',
    email: '',
    academicDisciplines: [
      {academicDisciplineId: '02015003', academicDisciplineName: 'Korean Studies'},
      {academicDisciplineId: '02016', academicDisciplineName: 'English Language and Literature'},
      {academicDisciplineId: '02016001', academicDisciplineName: 'Children' + "'" +'s and Young Adult Literature'},
      {academicDisciplineId: '02016002', academicDisciplineName: 'Literature in English, Anglophone outside British Isles and North America'},
      {academicDisciplineId: '02016003', academicDisciplineName: 'Literature in English, British Isles'},
      {academicDisciplineId: '02016004', academicDisciplineName: 'Literature in English, North America'},
      {academicDisciplineId: '02016005', academicDisciplineName: 'Literature in English, North America, Ethnic and Cultural Minority'},
      {academicDisciplineId: '02016006', academicDisciplineName: 'Other English Language and Literature'},
      {academicDisciplineId: '02017', academicDisciplineName: 'European Languages and Societies'},
      {academicDisciplineId: '02018', academicDisciplineName: 'Feminist, Gender, and Sexuality Studies'},
      {academicDisciplineId: '02018001', academicDisciplineName: 'Lesbian, Gay, Bisexual, and Transgender Studies'},
      {academicDisciplineId: '02018002', academicDisciplineName: 'Women' + "'" + 's Studies'},
      {academicDisciplineId: '02018003', academicDisciplineName: 'Other Feminist, Gender, and Sexuality Studies'},
      {academicDisciplineId: '02019', academicDisciplineName: 'Film and Media Studies'},
      {academicDisciplineId: '02019001', academicDisciplineName: 'Film Production'},
      {academicDisciplineId: '02019002', academicDisciplineName: 'Screenwriting'},
      {academicDisciplineId: '02019003', academicDisciplineName: 'Visual Studies'},
      {academicDisciplineId: '02019004', academicDisciplineName: 'Other Film and Media Studies'},
      {academicDisciplineId: '02020', academicDisciplineName: 'Fine Arts'},
      {academicDisciplineId: '02021', academicDisciplineName: 'French and Francophone Language and Literature'},
      {academicDisciplineId: '02021001', academicDisciplineName: 'French and Francophone Literature'},
      {academicDisciplineId: '02021002', academicDisciplineName: 'French Linguistics'},
      {academicDisciplineId: '02021003', academicDisciplineName: 'Other French and Francophone Language and Literature'},
      {academicDisciplineId: '02022', academicDisciplineName: 'German Language and Literature'},
      {academicDisciplineId: '02022001', academicDisciplineName: 'German Linguistics'},
      {academicDisciplineId: '02022002', academicDisciplineName: 'German Literature'},
      {academicDisciplineId: '02022003', academicDisciplineName: 'Other German Language and Literature'},
      {academicDisciplineId: '02023', academicDisciplineName: 'History'},
      {academicDisciplineId: '02023001', academicDisciplineName: 'African History'},
      {academicDisciplineId: '02023002', academicDisciplineName: 'Asian History'},
      {academicDisciplineId: '02023003', academicDisciplineName: 'Canadian History'},
      {academicDisciplineId: '02023004', academicDisciplineName: 'Cultural History'},
      {academicDisciplineId: '02023005', academicDisciplineName: 'Diplomatic History'}
    ]

  },
];
