export const academicDisciplineData = [
  {"academicDisciplineId": "01", "academicDisciplineName": "Architecture"},
  {"academicDisciplineId": "01001", "academicDisciplineName": "Architectural Engineering"},
  {"academicDisciplineId": "01002", "academicDisciplineName": "Architectural History and Criticism"},
  {"academicDisciplineId": "01003", "academicDisciplineName": "Architectural Technology"},
  {"academicDisciplineId": "01004", "academicDisciplineName": "Construction Engineering"},
  {"academicDisciplineId": "01005", "academicDisciplineName": "Cultural Resource Management and Policy Analysis"},
  {"academicDisciplineId": "01006", "academicDisciplineName": "Environmental Design"},
  {"academicDisciplineId": "01007", "academicDisciplineName": "Historic Preservation and Conservation"},
  {"academicDisciplineId": "01008", "academicDisciplineName": "Interior Architecture"},
  {"academicDisciplineId": "01009", "academicDisciplineName": "Landscape Architecture"},
  {"academicDisciplineId": "01010", "academicDisciplineName": "Urban, Community and Regional Planning"},
  {"academicDisciplineId": "01011", "academicDisciplineName": "Other Architecture"},
  {"academicDisciplineId": "02", "academicDisciplineName": "Arts and Humanities"},
  {"academicDisciplineId": "02001", "academicDisciplineName": "African Languages and Societies"},
  {"academicDisciplineId": "02002", "academicDisciplineName": "American Studies"},
  {"academicDisciplineId": "02002001", "academicDisciplineName": "American Film Studies"},
  {"academicDisciplineId": "02002002", "academicDisciplineName": "American Literature"},
  {"academicDisciplineId": "02002003", "academicDisciplineName": "American Material Culture"},
  {"academicDisciplineId": "02002004", "academicDisciplineName": "American Popular Culture"},
  {"academicDisciplineId": "02002005", "academicDisciplineName": "Other American Studies"},
  {"academicDisciplineId": "02003", "academicDisciplineName": "Appalachian Studies"},
  {"academicDisciplineId": "02004", "academicDisciplineName": "Art and Design"},
  {"academicDisciplineId": "02004001", "academicDisciplineName": "Art and Materials Conservation"},
  {"academicDisciplineId": "02004002", "academicDisciplineName": "Book and Paper"},
  {"academicDisciplineId": "02004003", "academicDisciplineName": "Ceramic Arts"},
  {"academicDisciplineId": "02004004", "academicDisciplineName": "Fashion Design"},
  {"academicDisciplineId": "02004005", "academicDisciplineName": "Fiber, Textile, and Weaving Arts"},
  {"academicDisciplineId": "02004006", "academicDisciplineName": "Game Design"},
  {"academicDisciplineId": "02004007", "academicDisciplineName": "Graphic Design"},
  {"academicDisciplineId": "02004008", "academicDisciplineName": "Illustration"},
  {"academicDisciplineId": "02004009", "academicDisciplineName": "Industrial and Product Design"},
  {"academicDisciplineId": "02004010", "academicDisciplineName": "Interactive Arts"},
  {"academicDisciplineId": "02004011", "academicDisciplineName": "Interdisciplinary Arts and Media"},
  {"academicDisciplineId": "02004012", "academicDisciplineName": "Metal and Jewelry Arts"},
  {"academicDisciplineId": "02004013", "academicDisciplineName": "Painting"},
  {"academicDisciplineId": "02004014", "academicDisciplineName": "Printmaking"},
  {"academicDisciplineId": "02004015", "academicDisciplineName": "Sculpture"},
  {"academicDisciplineId": "02005", "academicDisciplineName": "Art Practice"},
  {"academicDisciplineId": "02006", "academicDisciplineName": "Audio Arts and Acoustics"},
  {"academicDisciplineId": "02007", "academicDisciplineName": "Australian Studies"},
  {"academicDisciplineId": "02008", "academicDisciplineName": "Basque Studies"},
  {"academicDisciplineId": "0209", "academicDisciplineName": "Celtic Studies"},
  {"academicDisciplineId": "02010", "academicDisciplineName": "Classics"},
  {"academicDisciplineId": "02010001", "academicDisciplineName": "Ancient History, Greek and Roman through Late Antiquity"},
  {"academicDisciplineId": "02010002", "academicDisciplineName": "Ancient Philosophy"},
  {"academicDisciplineId": "02010003", "academicDisciplineName": "Byzantine and Modern Greek"},
  {"academicDisciplineId": "02010004", "academicDisciplineName": "Classical Archaeology and Art History"},
  {"academicDisciplineId": "02010005", "academicDisciplineName": "Classical Literature and Philology"},
  {"academicDisciplineId": "02010006", "academicDisciplineName": "Indo-European Linguistics and Philology"}
];
